- hosts: localhost
  connection: local
  become: yes
  
  collections:
    - community.general
  
  tasks:
    - name: Update the repository cache and update all packages
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - bpytop
        - cmatrix
        - default-jdk
        - flatpak
        - fonts-firacode
        - fonts-font-awesome
        - fonts-powerline
        - ghc
        - kitty
        - neofetch
        - neovim
        - nextcloud-desktop
        - openconnect
        - syncthing-gtk
        - texlive-full
        - zsh
    
    - name: Add flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: user
        
    - name: Install Bitwarden
      community.general.flatpak:
        name: com.bitwarden.desktop
        state: present
        remote: flathub
